#Análise Descritiva TO

In [ ]:
#Carregando os pacotes

In [ ]:
import pandas as pd  # processamento de bancos de dados
import numpy as np  # processamento numérico
import matplotlib.pyplot as plt  # geração de gráficos
import seaborn as sns  # geração de gráficos alternativos

# Configuração de gráficos no notebook
%matplotlib inline
plt.rcParams["figure.figsize"] = [10, 5]
plt.style.use("fivethirtyeight")
%config InlineBackend.figure_format = 'retina'

# Configurações de fonte e matemática
from matplotlib import rc
rc('font', **{'family': 'sans-serif', 'sans-serif': ['DejaVu Sans'], 'size': 10})
rc('mathtext', **{'default': 'regular'})

In [ ]:
df = pd.read_csv("dadosTO_entregavel_1_2015_2024.csv",sep=",")

In [ ]:
df.shape

(514, 25)

In [ ]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'bacilosc_4', 'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac', 'pop', 'front', 'cura',
       'faixa_etaria2', 'contato_maior5', 'escola_faixa',
       'tempo_diag_trat_14'],
      dtype='object')

In [ ]:
df['pop'].describe()

count       514.000000
mean     120962.564202
std      116867.432044
min        1470.000000
25%       10325.000000
50%       85125.000000
75%      171301.000000
max      302692.000000
Name: pop, dtype: float64

In [ ]:
import pandas as pd

# Criação da variável categórica com pd.cut
df['pop_grupo'] = pd.cut(
    df['pop'],
    bins=[-float('inf'),50000, 1000000, float('inf')],
    labels=['< 50000', '50000 a 1000000', '>1000000']
)

In [ ]:
df['pop_grupo'].value_counts(dropna=False)

pop_grupo
50000 a 1000000    306
< 50000            208
>1000000             0
Name: count, dtype: int64

In [ ]:
df['ano_grupo'] = pd.cut(
    df['nu_ano'],
    bins=[2014, 2022, float('inf')],
    labels=['2015-2022', '2023-2024']
)

In [ ]:
df['ano_grupo'].value_counts(dropna=False)

ano_grupo
2015-2022    395
2023-2024    119
Name: count, dtype: int64

In [ ]:
#Lista de variáveis com o desfecho
lista_variaveis = ['cura','ano_grupo','pop_grupo','front', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'bacilosc_4', 'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac','pop_grupo',
       'faixa_etaria2', 'contato_maior5', 'escola_faixa',
       'tempo_diag_trat_14']

##Proporção dos preditores e desfecho

In [ ]:
for coluna in lista_variaveis:
    print(f"\n==== Variável: {coluna} ====")

    # Frequência absoluta
    freq_abs = df[coluna].value_counts(dropna=False)

    # Frequência relativa (em %)
    freq_rel = df[coluna].value_counts(normalize=True, dropna=False) * 100

    # Juntar em um único DataFrame para visualização
    tabela = pd.DataFrame({
        'Frequência Absoluta': freq_abs,
        'Frequência Relativa (%)': freq_rel.round(2)
    })

    print(tabela)

==== Variável: cura ====
      Frequência Absoluta  Frequência Relativa (%)
cura
1                     446                    86.77
0                      68                    13.23

==== Variável: ano_grupo ====
           Frequência Absoluta  Frequência Relativa (%)
ano_grupo
2015-2022                  395                    76.85
2023-2024                  119                    23.15

==== Variável: pop_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
pop_grupo
50000 a 1000000                  306                    59.53
< 50000                          208                    40.47
>1000000                           0                     0.00

==== Variável: front ====
       Frequência Absoluta  Frequência Relativa (%)
front
0                      514                    100.0

==== Variável: cs_sexo ====
         Frequência Absoluta  Frequência Relativa (%)
cs_sexo
1                        374                    72.76
0                        140                    27.24

==== Variável: cs_raca ====
         Frequência Absoluta  Frequência Relativa (%)
cs_raca
4.0                      376                    73.15
2.0                       64                    12.45
1.0                       64                    12.45
NaN                       10                     1.95

==== Variável: raiox_tora ====
            Frequência Absoluta  Frequência Relativa (%)
raiox_tora
1.0                         338                    65.76
NaN                         162                    31.52
0.0                          14                     2.72

==== Variável: agravalcoo ====
            Frequência Absoluta  Frequência Relativa (%)
agravalcoo
0.0                         392                    76.26
1.0                         111                    21.60
NaN                          11                     2.14

==== Variável: agravdiabe ====
            Frequência Absoluta  Frequência Relativa (%)
agravdiabe
0.0                         442                    85.99
1.0                          61                    11.87
NaN                          11                     2.14

==== Variável: agravdoenc ====
            Frequência Absoluta  Frequência Relativa (%)
agravdoenc
0.0                         489                    95.14
1.0                          17                     3.31
NaN                           8                     1.56

==== Variável: bacilosc_e ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_e
1.0                         389                    75.68
0.0                          67                    13.04
NaN                          58                    11.28

==== Variável: cultura_es ====
            Frequência Absoluta  Frequência Relativa (%)
cultura_es
NaN                         320                    62.26
1.0                         159                    30.93
0.0                          35                     6.81

==== Variável: bacilosc_2 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_2
NaN                         240                    46.69
0.0                         229                    44.55
1.0                          45                     8.75

==== Variável: bacilosc_4 ====
            Frequência Absoluta  Frequência Relativa (%)
bacilosc_4
0.0                         263                    51.17
NaN                         243                    47.28
1.0                           8                     1.56

==== Variável: tratsup_at ====
            Frequência Absoluta  Frequência Relativa (%)
tratsup_at
1.0                         325                    63.23
0.0                         178                    34.63
NaN                          11                     2.14

==== Variável: pop_liber ====
           Frequência Absoluta  Frequência Relativa (%)
pop_liber
0.0                        460                    89.49
1.0                         50                     9.73
NaN                          4                     0.78

==== Variável: pop_rua ====
         Frequência Absoluta  Frequência Relativa (%)
pop_rua
0.0                      497                    96.69
1.0                       10                     1.95
NaN                        7                     1.36

==== Variável: pop_imig ====
          Frequência Absoluta  Frequência Relativa (%)
pop_imig
0.0                       505                    98.25
NaN                         5                     0.97
1.0                         4                     0.78

==== Variável: benef_gov ====
           Frequência Absoluta  Frequência Relativa (%)
benef_gov
0.0                        421                    81.91
1.0                         65                    12.65
NaN                         28                     5.45

==== Variável: agravdroga ====
            Frequência Absoluta  Frequência Relativa (%)
agravdroga
0.0                         446                    86.77
1.0                          49                     9.53
NaN                          19                     3.70

==== Variável: agravtabac ====
            Frequência Absoluta  Frequência Relativa (%)
agravtabac
0.0                         356                    69.26
1.0                         147                    28.60
NaN                          11                     2.14

==== Variável: pop_grupo ====
                 Frequência Absoluta  Frequência Relativa (%)
pop_grupo
50000 a 1000000                  306                    59.53
< 50000                          208                    40.47
>1000000                           0                     0.00

==== Variável: faixa_etaria2 ====
               Frequência Absoluta  Frequência Relativa (%)
faixa_etaria2
1.0                            213                    41.44
2.0                            158                    30.74
3.0                            106                    20.62
0.0                             37                     7.20

==== Variável: contato_maior5 ====
                Frequência Absoluta  Frequência Relativa (%)
contato_maior5
0.0                             432                    84.05
1.0                              79                    15.37
NaN                               3                     0.58

==== Variável: escola_faixa ====
              Frequência Absoluta  Frequência Relativa (%)
escola_faixa
0.0                           348                    67.70
1.0                           110                    21.40
NaN                            52                    10.12
10.0                            4                     0.78

==== Variável: tempo_diag_trat_14 ====
                    Frequência Absoluta  Frequência Relativa (%)
tempo_diag_trat_14
0.0                                 451                    87.74
1.0                                  60                    11.67
NaN                                   3                     0.58

In [ ]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = ['ano_grupo','pop_grupo','front', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'bacilosc_4', 'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac',
       'faixa_etaria2', 'contato_maior5', 'escola_faixa',
       'tempo_diag_trat_14']

In [ ]:
# Listas
lista_variavel_desfecho = ['cura']

lista_preditores = ['ano_grupo','pop_grupo','front', 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'cultura_es', 'bacilosc_2',
       'bacilosc_4', 'tratsup_at', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac',
       'faixa_etaria2', 'contato_maior5', 'escola_faixa',
       'tempo_diag_trat_14']

# Dicionário para salvar os resultados
resultados = {}

desfecho = lista_variavel_desfecho[0]

for var in lista_preditores:

    # Versão temporária sem NA (convertendo para object)
    temp_var = df[var].astype('object').where(df[var].notna(), 'NA')

    # Contagem
    tabela = (
        pd.DataFrame({var: temp_var, desfecho: df[desfecho]})
        .groupby([var, desfecho], dropna=False)
        .size()
        .rename("Frequência Absoluta")
        .reset_index()
    )

    # Frequência relativa
    tabela["Frequência Relativa (%)"] = (
        tabela["Frequência Absoluta"]
        / tabela.groupby(var)["Frequência Absoluta"].transform("sum")
        * 100
    ).round(2)

    resultados[var] = tabela

# Exibir
for var, tabela in resultados.items():
    print(f"\n==== Variável: {var} ====")
    print(tabela)

==== Variável: ano_grupo ====
   ano_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  2015-2022     0                   46                    11.65
1  2015-2022     1                  349                    88.35
2  2023-2024     0                   22                    18.49
3  2023-2024     1                   97                    81.51

==== Variável: pop_grupo ====
         pop_grupo  cura  Frequência Absoluta  Frequência Relativa (%)
0  50000 a 1000000     0                   40                    13.07
1  50000 a 1000000     1                  266                    86.93
2          < 50000     0                   28                    13.46
3          < 50000     1                  180                    86.54

==== Variável: front ====
   front  cura  Frequência Absoluta  Frequência Relativa (%)
0      0     0                   68                    13.23
1      0     1                  446                    86.77

==== Variável: cs_sexo ====
   cs_sexo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0     0                    9                     6.43
1        0     1                  131                    93.57
2        1     0                   59                    15.78
3        1     1                  315                    84.22

==== Variável: cs_raca ====
  cs_raca  cura  Frequência Absoluta  Frequência Relativa (%)
0     1.0     0                    5                     7.81
1     1.0     1                   59                    92.19
2     2.0     0                   13                    20.31
3     2.0     1                   51                    79.69
4     4.0     0                   49                    13.03
5     4.0     1                  327                    86.97
6      NA     0                    1                    10.00
7      NA     1                    9                    90.00

==== Variável: raiox_tora ====
  raiox_tora  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                    1                     7.14
1        0.0     1                   13                    92.86
2        1.0     0                   53                    15.68
3        1.0     1                  285                    84.32
4         NA     0                   14                     8.64
5         NA     1                  148                    91.36

==== Variável: agravalcoo ====
  agravalcoo  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   43                    10.97
1        0.0     1                  349                    89.03
2        1.0     0                   23                    20.72
3        1.0     1                   88                    79.28
4         NA     0                    2                    18.18
5         NA     1                    9                    81.82

==== Variável: agravdiabe ====
  agravdiabe  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   58                    13.12
1        0.0     1                  384                    86.88
2        1.0     0                    7                    11.48
3        1.0     1                   54                    88.52
4         NA     0                    3                    27.27
5         NA     1                    8                    72.73

==== Variável: agravdoenc ====
  agravdoenc  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   65                    13.29
1        0.0     1                  424                    86.71
2        1.0     0                    2                    11.76
3        1.0     1                   15                    88.24
4         NA     0                    1                    12.50
5         NA     1                    7                    87.50

==== Variável: bacilosc_e ====
  bacilosc_e  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   11                    16.42
1        0.0     1                   56                    83.58
2        1.0     0                   47                    12.08
3        1.0     1                  342                    87.92
4         NA     0                   10                    17.24
5         NA     1                   48                    82.76

==== Variável: cultura_es ====
  cultura_es  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                    3                     8.57
1        0.0     1                   32                    91.43
2        1.0     0                   24                    15.09
3        1.0     1                  135                    84.91
4         NA     0                   41                    12.81
5         NA     1                  279                    87.19

==== Variável: bacilosc_2 ====
  bacilosc_2  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   10                     4.37
1        0.0     1                  219                    95.63
2        1.0     0                    6                    13.33
3        1.0     1                   39                    86.67
4         NA     0                   52                    21.67
5         NA     1                  188                    78.33

==== Variável: bacilosc_4 ====
  bacilosc_4  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                    8                     3.04
1        0.0     1                  255                    96.96
2        1.0     0                    1                    12.50
3        1.0     1                    7                    87.50
4         NA     0                   59                    24.28
5         NA     1                  184                    75.72

==== Variável: tratsup_at ====
  tratsup_at  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   31                    17.42
1        0.0     1                  147                    82.58
2        1.0     0                   33                    10.15
3        1.0     1                  292                    89.85
4         NA     0                    4                    36.36
5         NA     1                    7                    63.64

==== Variável: pop_liber ====
  pop_liber  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                   64                    13.91
1       0.0     1                  396                    86.09
2       1.0     0                    4                     8.00
3       1.0     1                   46                    92.00
4        NA     1                    4                   100.00

==== Variável: pop_rua ====
  pop_rua  cura  Frequência Absoluta  Frequência Relativa (%)
0     0.0     0                   64                    12.88
1     0.0     1                  433                    87.12
2     1.0     0                    3                    30.00
3     1.0     1                    7                    70.00
4      NA     0                    1                    14.29
5      NA     1                    6                    85.71

==== Variável: pop_imig ====
  pop_imig  cura  Frequência Absoluta  Frequência Relativa (%)
0      0.0     0                   66                    13.07
1      0.0     1                  439                    86.93
2      1.0     0                    1                    25.00
3      1.0     1                    3                    75.00
4       NA     0                    1                    20.00
5       NA     1                    4                    80.00

==== Variável: benef_gov ====
  benef_gov  cura  Frequência Absoluta  Frequência Relativa (%)
0       0.0     0                   55                    13.06
1       0.0     1                  366                    86.94
2       1.0     0                    8                    12.31
3       1.0     1                   57                    87.69
4        NA     0                    5                    17.86
5        NA     1                   23                    82.14

==== Variável: agravdroga ====
  agravdroga  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   51                    11.43
1        0.0     1                  395                    88.57
2        1.0     0                   16                    32.65
3        1.0     1                   33                    67.35
4         NA     0                    1                     5.26
5         NA     1                   18                    94.74

==== Variável: agravtabac ====
  agravtabac  cura  Frequência Absoluta  Frequência Relativa (%)
0        0.0     0                   31                     8.71
1        0.0     1                  325                    91.29
2        1.0     0                   35                    23.81
3        1.0     1                  112                    76.19
4         NA     0                    2                    18.18
5         NA     1                    9                    81.82

==== Variável: faixa_etaria2 ====
   faixa_etaria2  cura  Frequência Absoluta  Frequência Relativa (%)
0            0.0     0                    5                    13.51
1            0.0     1                   32                    86.49
2            1.0     0                   34                    15.96
3            1.0     1                  179                    84.04
4            2.0     0                   17                    10.76
5            2.0     1                  141                    89.24
6            3.0     0                   12                    11.32
7            3.0     1                   94                    88.68

==== Variável: contato_maior5 ====
  contato_maior5  cura  Frequência Absoluta  Frequência Relativa (%)
0            0.0     0                   60                    13.89
1            0.0     1                  372                    86.11
2            1.0     0                    7                     8.86
3            1.0     1                   72                    91.14
4             NA     0                    1                    33.33
5             NA     1                    2                    66.67

==== Variável: escola_faixa ====
  escola_faixa  cura  Frequência Absoluta  Frequência Relativa (%)
0          0.0     0                   48                    13.79
1          0.0     1                  300                    86.21
2          1.0     0                   10                     9.09
3          1.0     1                  100                    90.91
4         10.0     0                    1                    25.00
5         10.0     1                    3                    75.00
6           NA     0                    9                    17.31
7           NA     1                   43                    82.69

==== Variável: tempo_diag_trat_14 ====
  tempo_diag_trat_14  cura  Frequência Absoluta  Frequência Relativa (%)
0                0.0     0                   57                    12.64
1                0.0     1                  394                    87.36
2                1.0     0                    9                    15.00
3                1.0     1                   51                    85.00
4                 NA     0                    2                    66.67
5                 NA     1                    1                    33.33