In [1]:
!pip install tqdm>=4.64.1

In [2]:
!pip install pysus

Requirement already satisfied: pysus in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.12/dist-packages (from pysus) (1.4.0)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from pysus) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (0.12.5)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /usr/local/lib/python3.12/dist-packages (from pysus) (1.2.2)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.0.7)
Requirement already satisfied: elasticsearch==7.16.2 in /usr/local/lib/python3.12/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (7.16.2)
Requirement already satisfied: fastparquet<=2024.11.0,>=2023.10.1 in /usr/local/lib/python3.12/dist-packages (from pysus) (2024.11.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (4.15.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (0.6.0)
Requirement already satisfied: numpy<3,>1 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (18.1.0)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.8.2)
Requirement already satisfied: tqdm==4.64.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (4.15.0)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.6.16)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (1.26.20)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (2026.1.4)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil==2.8.2->pysus) (1.17.0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (25.0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.2->pysus) (2025.3)
Requirement already satisfied: cffi<2,>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->pysus) (1.17.1)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.14)

In [3]:
!pip install ydata-profiling

Collecting ydata-profiling
  Using cached ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Using cached visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Using cached minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Using cached filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Using cached phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Collecting tqdm<5,>=4.66.3 (from ydata-profiling)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Using cached multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.4.4)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Using cached ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.5)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Using cached dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.8.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 9.9 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 12.6 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 44.3 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 38.8 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 4.9 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 5.3 MB/s eta 0:00:00
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 2.0 MB/s eta 0:00:00
Installing collected packages: puremagic, minify-html, filetype, tqdm, multimethod, dacite, imagehash, visions, phik, ydata-profiling
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.64.0
    Uninstalling tqdm-4.64.0:
      Successfully uninstalled tqdm-4.64.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pysus 1.0.0 requires tqdm==4.64.0, but you have tqdm 4.67.1 which is incompatible.
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-1.30 tqdm-4.67.1 visions-0.8.1 ydata-profiling-4.18.1

In [4]:
!pip list

Package                                  Version
---------------------------------------- ------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aioftp                                   0.21.4
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.3
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.12.1
anywidget                                0.9.21
apsw                                     3.51.1.0
apswutils                                0.1.2
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
astropy                                  7.2.0
astropy-iers-data                        0.2026.1.5.0.43.43
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    25.4.0
audioread                                3.1.0
Authlib                                  1.6.6
autograd                                 1.8.0
babel                                    2.17.0
backcall                                 0.2.0
beartype                                 0.22.9
beautifulsoup4                           4.13.5
betterproto                              2.0.0b6
bigframes                                2.31.0
bigquery-magics                          0.10.3
bigtree                                  0.12.5
bleach                                   6.3.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.1.0
blosc2                                   3.12.2
bokeh                                    3.7.3
Bottleneck                               1.4.2
bqplot                                   0.12.45
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               6.2.4
catalogue                                2.0.10
certifi                                  2026.1.4
cffi                                     1.17.1
chardet                                  5.2.0
charset-normalizer                       3.4.4
chex                                     0.1.90
clarabel                                 0.11.1
click                                    8.3.1
click-plugins                            1.1.1.2
cligj                                    0.7.2
cloudpathlib                             0.23.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.1.0
colorlover                               0.3.0
colour                                   0.1.5
community                                1.0.0b1
confection                               0.1.5
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             43.0.3
cufflinks                                0.17.3
curl_cffi                                0.14.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dacite                                   1.9.2
dask                                     2025.12.0
dataproc-spark-connect                   1.0.1
datasets                                 4.0.0
dateparser                               1.2.2
db-dtypes                                1.5.0
dbfread                                  2.0.7
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
deprecation                              2.1.0
diffusers                                0.36.0
dill                                     0.3.8
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.9
docstring_parser                         0.17.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.5.24
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.1
elasticsearch                            7.16.2
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.8.1
et_xmlfile                               2.0.0
etils                                    1.13.0
etuples                                  0.3.10
Farama-Notifications                     0.0.4
fastai                                   2.8.6
fastapi                                  0.123.10
fastcore                                 1.11.2
fastdownload                             0.0.7
fastjsonschema                           2.21.2
fastlite                                 0.2.3
fastparquet                              2024.11.0
fastprogress                             1.1.3
fasttransform                            0.0.2
ffmpy                                    1.0.0
filelock                                 3.20.2
filetype                                 1.2.0
fiona                                    1.10.1
firebase-admin                           6.9.0
Flask                                    3.1.2
flatbuffers                              25.12.19
flax                                     0.10.7
folium                                   0.20.0
fonttools                                4.61.1
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.7.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.0
geemap                                   0.35.3
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.2
geopy                                    2.4.1
giddy                                    2.3.8
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.46
glob2                                    0.7
google                                   3.0.0
google-adk                               1.21.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.29.0
google-api-python-client                 2.187.0
google-auth                              2.43.0
google-auth-httplib2                     0.3.0
google-auth-oauthlib                     1.2.2
google-cloud-aiplatform                  1.130.0
google-cloud-appengine-logging           1.7.0
google-cloud-audit-log                   0.4.0
google-cloud-bigquery                    3.40.0
google-cloud-bigquery-connection         1.19.0
google-cloud-bigquery-storage            2.36.0
google-cloud-bigtable                    2.35.0
google-cloud-core                        2.5.0
google-cloud-dataproc                    5.23.0
google-cloud-datastore                   2.23.0
google-cloud-discoveryengine             0.13.12
google-cloud-firestore                   2.22.0
google-cloud-functions                   1.21.0
google-cloud-language                    2.18.0
google-cloud-logging                     3.13.0
google-cloud-monitoring                  2.28.0
google-cloud-resource-manager            1.15.0
google-cloud-secret-manager              2.26.0
google-cloud-spanner                     3.61.0
google-cloud-speech                      2.35.0
google-cloud-storage                     3.7.0
google-cloud-trace                       1.17.0
google-cloud-translate                   3.23.0
google-colab                             1.0.0
google-crc32c                            1.8.0
google-genai                             1.55.0
google-generativeai                      0.8.6
google-pasta                             0.2.0
google-resumable-media                   2.8.0
googleapis-common-protos                 1.72.0
googledrivedownloader                    1.1.0
gradio                                   5.50.0
gradio_client                            1.14.0
graphviz                                 0.21
greenlet                                 3.3.0
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.3
grpc-interceptor                         0.15.4
grpcio                                   1.76.0
grpcio-status                            1.71.2
grpclib                                  0.4.9
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.2.3
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.7.3
h5py                                     3.15.1
hdbscan                                  0.8.41
hf_transfer                              0.1.9
hf-xet                                   1.2.0
highspy                                  1.12.0
holidays                                 0.88
holoviews                                1.22.1
hpack                                    4.1.0
html5lib                                 1.1
httpcore                                 1.0.9
httpimport                               1.4.1
httplib2                                 0.31.0
httptools                                0.7.1
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface-hub                          0.36.0
humanize                                 4.15.0
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.11
ImageHash                                4.3.2
ImageIO                                  2.37.2
imageio-ffmpeg                           0.6.0
imagesize                                1.4.1
imbalanced-learn                         0.14.1
immutabledict                            4.2.2
importlib_metadata                       8.7.1
importlib_resources                      6.5.2
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.1
intel-openmp                             2025.3.1
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipytree                                  0.2.2
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.0.2
jaraco.functools                         4.4.0
jax                                      0.7.2
jaxlib                                   0.7.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.12.0
joblib                                   1.5.3
jsonpatch                                1.33
jsonpickle                               4.1.1
jsonpointer                              3.0.0
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.0
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.14.0
jupyter_server_terminals                 0.5.3
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.18.1
kaggle                                   1.7.4.5
kagglehub                                0.3.13
keras                                    3.10.0
keras-hub                                0.21.1
keras-nlp                                0.21.1
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.4.9
langchain                                1.2.3
langchain-core                           1.2.6
langgraph                                1.0.5
langgraph-checkpoint                     3.0.1
langgraph-prebuilt                       1.0.5
langgraph-sdk                            0.3.1
langsmith                                0.6.1
lark                                     1.3.1
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy_loader                              0.4
libclang                                 18.1.1
libpysal                                 4.14.0
librosa                                  0.11.0
lightgbm                                 4.6.0
linkify-it-py                            2.0.3
llvmlite                                 0.43.0
locket                                   1.0.0
logical-unification                      0.4.7
loguru                                   0.6.0
lxml                                     6.0.2
Mako                                     1.3.10
mapclassify                              2.10.0
Markdown                                 3.10
markdown-it-py                           4.0.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.1
matplotlib-venn                          1.1.2
mcp                                      1.25.0
mdit-py-plugins                          0.5.0
mdurl                                    0.1.2
mgwr                                     2.2.1
minify_html                              0.18.1
miniKanren                               1.0.5
missingno                                0.5.2
mistune                                  3.2.0
mizani                                   0.13.5
mkl                                      2025.3.0
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
mmh3                                     5.2.0
momepy                                   0.11.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.1.2
multidict                                6.7.0
multimethod                              1.12
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.12
murmurhash                               1.0.15
music21                                  9.9.1
namex                                    0.1.0
narwhals                                 2.15.0
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.4
nbconvert                                7.16.6
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6.1
nibabel                                  5.3.3
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.60.0
numexpr                                  2.14.1
numpy                                    2.0.2
nvidia-nccl-cu12                         2.29.2
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.0
onemkl-license                           2025.3.0
openai                                   2.14.0
opencv-contrib-python                    4.12.0.88
opencv-python                            4.12.0.88
opencv-python-headless                   4.12.0.88
openpyxl                                 3.1.5
opentelemetry-api                        1.37.0
opentelemetry-exporter-gcp-logging       1.11.0a0
opentelemetry-exporter-gcp-monitoring    1.11.0a0
opentelemetry-exporter-gcp-trace         1.11.0
opentelemetry-exporter-otlp-proto-common 1.37.0
opentelemetry-exporter-otlp-proto-http   1.37.0
opentelemetry-proto                      1.37.0
opentelemetry-resourcedetector-gcp       1.11.0a0
opentelemetry-sdk                        1.37.0
opentelemetry-semantic-conventions       0.58b0
opt_einsum                               3.4.0
optax                                    0.2.6
optree                                   0.18.0
orbax-checkpoint                         0.11.31
orjson                                   3.11.5
ormsgpack                                1.12.1
osqp                                     1.0.5
overrides                                7.7.0
packaging                                25.0
pandas                                   2.2.2
pandas-datareader                        0.10.0
pandas-gbq                               0.30.0
pandas-stubs                             2.2.2.240909
pandocfilters                            1.5.1
panel                                    1.8.5
param                                    2.3.1
parso                                    0.8.5
parsy                                    2.2
partd                                    1.4.2
patsy                                    1.0.2
peewee                                   3.19.0
peft                                     0.18.0
pexpect                                  4.9.0
phik                                     0.12.5
pickleshare                              0.7.5
pillow                                   11.3.0
pip                                      24.1.2
platformdirs                             4.5.1

In [5]:
!pip install pysus

Requirement already satisfied: pysus in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.12/dist-packages (from pysus) (1.4.0)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from pysus) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (0.12.5)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /usr/local/lib/python3.12/dist-packages (from pysus) (1.2.2)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.0.7)
Requirement already satisfied: elasticsearch==7.16.2 in /usr/local/lib/python3.12/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (7.16.2)
Requirement already satisfied: fastparquet<=2024.11.0,>=2023.10.1 in /usr/local/lib/python3.12/dist-packages (from pysus) (2024.11.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (4.15.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (0.6.0)
Requirement already satisfied: numpy<3,>1 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (18.1.0)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.8.2)
Collecting tqdm==4.64.0 (from pysus)
  Using cached tqdm-4.64.0-py2.py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from pysus) (4.15.0)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (2.6.16)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.12/dist-packages (from pysus) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (1.26.20)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus) (2026.1.4)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil==2.8.2->pysus) (1.17.0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus) (25.0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.2->pysus) (2025.3)
Requirement already satisfied: cffi<2,>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->pysus) (1.17.1)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.12/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.14)
Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.1 requires tqdm<5,>=4.66.3, but you have tqdm 4.64.0 which is incompatible.
tobler 0.13.0 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
dopamine-rl 4.1.2 requires tqdm>=4.64.1, but you have tqdm 4.64.0 which is incompatible.
datasets 4.0.0 requires tqdm>=4.66.3, but you have tqdm 4.64.0 which is incompatible.
spopt 0.7.0 requires tqdm>=4.66.0, but you have tqdm 4.64.0 which is incompatible.
dataproc-spark-connect 1.0.1 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
momepy 0.11.0 requires tqdm>=4.65, but you have tqdm 4.64.0 which is incompatible.
Successfully installed tqdm-4.64.0

In [6]:
from pysus.ftp.databases.sinan import SINAN
from ydata_profiling import ProfileReport
sinan = SINAN().load()
sinan.diseases

{'ACBI': 'Acidente de trabalho com material biológico',
 'ACGR': 'Acidente de trabalho',
 'ANIM': 'Acidente por Animais Peçonhentos',
 'ANTR': 'Atendimento Antirrabico',
 'BOTU': 'Botulismo',
 'CANC': 'Cancêr relacionado ao trabalho',
 'CHAG': 'Doença de Chagas Aguda',
 'CHIK': 'Febre de Chikungunya',
 'COLE': 'Cólera',
 'COQU': 'Coqueluche',
 'DENG': 'Dengue',
 'DERM': 'Dermatoses ocupacionais',
 'DIFT': 'Difteria',
 'ESQU': 'Esquistossomose',
 'EXAN': 'Doença exantemáticas',
 'FMAC': 'Febre Maculosa',
 'FTIF': 'Febre Tifóide',
 'HANS': 'Hanseníase',
 'HANT': 'Hantavirose',
 'HEPA': 'Hepatites Virais',
 'IEXO': 'Intoxicação Exógena',
 'INFL': 'Influenza Pandêmica',
 'LEIV': 'Leishmaniose Visceral',
 'LEPT': 'Leptospirose',
 'LERD': 'LER/Dort',
 'LTAN': 'Leishmaniose Tegumentar Americana',
 'MALA': 'Malária',
 'MENI': 'Meningite',
 'MENT': 'Transtornos mentais relacionados ao trabalho',
 'NTRA': 'Notificação de Tracoma',
 'PAIR': 'Perda auditiva por ruído relacionado ao trabalho',
 'PEST': 'Peste',
 'PFAN': 'Paralisia Flácida Aguda',
 'PNEU': 'Pneumoconioses realacionadas ao trabalho',
 'RAIV': 'Raiva',
 'SDTA': 'Surto Doenças Transmitidas por Alimentos',
 'SIFA': 'Sífilis Adquirida',
 'SIFC': 'Sífilis Congênita',
 'SIFG': 'Sífilis em Gestante',
 'SRC': 'Síndrome da Rubéola Congênia',
 'TETA': 'Tétano Acidental',
 'TETN': 'Tétano Neonatal',
 'TOXC': 'Toxoplasmose Congênita',
 'TOXG': 'Toxoplasmose Gestacional',
 'TRAC': 'Inquérito de Tracoma',
 'TUBE': 'Tuberculose',
 'VARC': 'Varicela',
 'VIOL': 'Violência doméstica, sexual e/ou outras violências',
 'ZIKA': 'Zika Vírus'}

In [20]:
# Arquivos de Tuberculose
files = sinan.get_files(dis_code='ZIKA', year=[2018,2019,2020, 2021, 2022,2023, 2024])
zika2018,zika2019,zika2020,zika2021,zika2022,zika2023,zika2024=files

sinan.describe(zika2023)

{'name': 'ZIKABR23.dbc',
 'disease': 'Zika Vírus',
 'year': 2023,
 'size': '870.9 kB',
 'last_update': '2026-01-02 09:20AM'}

In [21]:
parquet = zika2018.download()
df2018 = parquet.to_dataframe()
print(df2018.shape)

(20584, 38)

In [22]:
parquet = zika2019.download()
df2019 = parquet.to_dataframe()
print(df2019.shape)

(30500, 38)

In [23]:
parquet = zika2020.download()
df2020 = parquet.to_dataframe()
print(df2020.shape)

(20867, 38)

In [24]:
parquet = zika2021.download()
df2021 = parquet.to_dataframe()
print(df2021.shape)

(19090, 38)

In [25]:
parquet = zika2022.download()
df2022 = parquet.to_dataframe()
print(df2022.shape)

(35121, 38)

In [26]:
parquet = zika2023.download()
df2023 = parquet.to_dataframe()
print(df2023.shape)

(36003, 38)

In [27]:
parquet = zika2024.download()
df2024 = parquet.to_dataframe()
print(df2024.shape)

(43676, 38)

In [ ]:
#unindo dataframes

In [29]:
import pandas as pd

# Supondo que os dataframes df2010, df2011, ..., df2023 já estejam carregados

# Lista para armazenar os DataFrames com a coluna 'ano' adicionada
dfs = []

# Iterando de 2010 a 2023 para adicionar a coluna 'ano' e armazenar os DataFrames
for ano in range(2018, 2025):
    # Cria uma cópia do DataFrame atual e adiciona a coluna 'ano'
    df = globals()[f"df{ano}"].copy()  # Acessa o DataFrame usando globals()
    df['ano'] = ano  # Adiciona a coluna 'ano' com o valor correspondente
    dfs.append(df)  # Adiciona o DataFrame modificado à lista

# Concatenando todos os DataFrames na lista 'dfs' em um único DataFrame
df_completo = pd.concat(dfs, ignore_index=True)

# Visualizando o resultado
df_completo

,TP_NOT,ID_AGRAVO,CS_SUSPEIT,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,...,DT_OBITO,DT_ENCERRA,CS_FLXRET,FLXRECEBI,TP_SISTEMA,TPUNINOT,ano,ID_UNIDADE,ANO_NASC,DT_DIGITA
0,2,A928,,2018-01-01,201801,2018,33,330490,,2017-12-28,...,,20180101,0,2,1,,2018,<NA>,<NA>,<NA>
1,2,A928,,2018-01-01,201801,2018,33,330490,,2017-12-29,...,,20180101,0,2,1,,2018,<NA>,<NA>,<NA>
2,2,A928,,2018-01-01,201801,2018,27,270800,1540,2017-12-31,...,,20180312,0,2,1,,2018,<NA>,<NA>,<NA>
3,2,A928,,2018-01-01,201801,2018,51,510650,1578,2018-01-01,...,,20180306,0,2,1,,2018,<NA>,<NA>,<NA>
4,2,A928,,2018-01-01,201801,2018,51,510650,1578,2017-12-31,...,,,2,2,1,,2018,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205836,2,A928,<NA>,2024-09-30,202440,2024,31,311000,1449,2024-09-29,...,,20241114,<NA>,<NA>,,,2024,2116456,1995,20241114
205837,2,A928,<NA>,2024-09-30,202440,2024,23,230440,1519,2024-09-28,...,,20241009,<NA>,<NA>,,,2024,2497654,2024,20241001
205838,2,A928,<NA>,2024-09-30,202440,2024,29,291170,1398,2024-09-30,...,,20241106,<NA>,<NA>,,,2024,2804034,1997,20241106
205839,2,A928,<NA>,2024-09-30,202440,2024,52,521190,1800,2024-09-25,...,,20241024,<NA>,<NA>,,,2024,2535556,1963,20241001
205840,2,A928,<NA>,2024-09-30,202440,2024,26,260550,5558,2024-09-29,...,,20241024,<NA>,<NA>,,,2024,2354209,2006,20241024

In [30]:
df_completo

,TP_NOT,ID_AGRAVO,CS_SUSPEIT,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,...,DT_OBITO,DT_ENCERRA,CS_FLXRET,FLXRECEBI,TP_SISTEMA,TPUNINOT,ano,ID_UNIDADE,ANO_NASC,DT_DIGITA
0,2,A928,,2018-01-01,201801,2018,33,330490,,2017-12-28,...,,20180101,0,2,1,,2018,<NA>,<NA>,<NA>
1,2,A928,,2018-01-01,201801,2018,33,330490,,2017-12-29,...,,20180101,0,2,1,,2018,<NA>,<NA>,<NA>
2,2,A928,,2018-01-01,201801,2018,27,270800,1540,2017-12-31,...,,20180312,0,2,1,,2018,<NA>,<NA>,<NA>
3,2,A928,,2018-01-01,201801,2018,51,510650,1578,2018-01-01,...,,20180306,0,2,1,,2018,<NA>,<NA>,<NA>
4,2,A928,,2018-01-01,201801,2018,51,510650,1578,2017-12-31,...,,,2,2,1,,2018,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205836,2,A928,<NA>,2024-09-30,202440,2024,31,311000,1449,2024-09-29,...,,20241114,<NA>,<NA>,,,2024,2116456,1995,20241114
205837,2,A928,<NA>,2024-09-30,202440,2024,23,230440,1519,2024-09-28,...,,20241009,<NA>,<NA>,,,2024,2497654,2024,20241001
205838,2,A928,<NA>,2024-09-30,202440,2024,29,291170,1398,2024-09-30,...,,20241106,<NA>,<NA>,,,2024,2804034,1997,20241106
205839,2,A928,<NA>,2024-09-30,202440,2024,52,521190,1800,2024-09-25,...,,20241024,<NA>,<NA>,,,2024,2535556,1963,20241001
205840,2,A928,<NA>,2024-09-30,202440,2024,26,260550,5558,2024-09-29,...,,20241024,<NA>,<NA>,,,2024,2354209,2006,20241024

In [31]:
df_completo.to_csv("/content/ZIKAcompleto_2018_2024.csv")